server.port: 8082

spring:
  application:
    name: billing
  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/testdata
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/billing

algashop:
  integrations:
    payment:
      provider: FASTPAY #FAKE
      fastpay:
        hostname: http://localhost:9995
        private-token: SSEewtC6Ps5yJLdB6SJmh1bqJXgRbCdf8ocDj2hU